const $ = id => document.getElementById(id);
const rand = (min,max)=>Math.floor(Math.random()*(max-min+1))+min;
const shuffle = arr => [...arr].sort(()=>Math.random()-.5);
const todayKey = () => new Date().toISOString().slice(0,10);
const weekKey = () => { const d=new Date(); const y=d.getFullYear(); const onejan=new Date(y,0,1); return `${y}-W${Math.ceil((((d-onejan)/86400000)+onejan.getDay()+1)/7)}`; };

const classLevels = [
  {level:1, name:'Foundations', ages:'4–6', max:10, topics:['counting','addition','subtraction','patterns']},
  {level:2, name:'Builder', ages:'7–8', max:50, topics:['addition','subtraction','multiplication','division','time','money']},
  {level:3, name:'Explorer', ages:'9–10', max:100, topics:['multiplication','division','fractions','geometry','word','patterns']},
  {level:4, name:'Champion', ages:'11–12', max:250, topics:['fractions','decimals','percent','ratio','algebra','word']},
  {level:5, name:'Genius', ages:'Advanced', max:500, topics:['algebra','percent','ratio','geometry','logic','word']}
];
const allTopics = {
  counting:{name:'Counting Kingdom',icon:'🔢',world:0}, addition:{name:'Addition Forest',icon:'🌳',world:0}, subtraction:{name:'Subtraction Cave',icon:'🕳️',world:0}, patterns:{name:'Pattern Temple',icon:'🏛️',world:1}, multiplication:{name:'Times Mountain',icon:'⛰️',world:1}, division:{name:'Division River',icon:'🌊',world:1}, fractions:{name:'Fraction Ocean',icon:'🍕',world:2}, decimals:{name:'Decimal Docks',icon:'⚓',world:2}, percent:{name:'Percent Park',icon:'🎯',world:2}, ratio:{name:'Ratio Ranch',icon:'⚖️',world:3}, geometry:{name:'Shape City',icon:'📐',world:3}, time:{name:'Clock Tower',icon:'⏰',world:3}, money:{name:'Market Math',icon:'🪙',world:3}, algebra:{name:'Algebra Galaxy',icon:'🚀',world:4}, logic:{name:'Logic Lab',icon:'🧠',world:4}, word:{name:'Story Problems',icon:'📖',world:4}
};
const worlds = [
  {name:'Forest Gate', icon:'🌲', story:'Save animals by mastering number basics.', boss:'Number Dragon', bossIcon:'🐉'},
  {name:'Mountain Trail', icon:'⛰️', story:'Power bridges with patterns and operations.', boss:'Times Troll', bossIcon:'🧌'},
  {name:'Crystal Island', icon:'🏝️', story:'Restore crystals using fractions, decimals, and percents.', boss:'Fraction Kraken', bossIcon:'🐙'},
  {name:'Clockwork City', icon:'🏙️', story:'Repair the city with time, money, ratios, and shapes.', boss:'Time Wizard', bossIcon:'🧙'},
  {name:'Algebra Galaxy', icon:'🌌', story:'Launch the rocket with advanced problem solving.', boss:'Algebra Robot', bossIcon:'🤖'}
];
const avatars = [
  {id:'fox', icon:'🦊', name:'Focus Fox', line:'Quick and clever'}, {id:'robot', icon:'🤖', name:'Robo Tutor', line:'Calm and precise'}, {id:'wizard', icon:'🧙', name:'Number Wizard', line:'Loves hard puzzles'}, {id:'panda', icon:'🐼', name:'Patient Panda', line:'Kind encouragement'}, {id:'dragon', icon:'🐲', name:'Brave Dragon', line:'Boss battle energy'}, {id:'lion', icon:'🦁', name:'Logic Lion', line:'Fearless thinker'}
];
const pets = [
  {id:'none', icon:'✨', name:'No Pet', cost:0}, {id:'cat', icon:'🐱', name:'Puzzle Cat', cost:80}, {id:'owl', icon:'🦉', name:'Wisdom Owl', cost:140}, {id:'dog', icon:'🐶', name:'Lucky Pup', cost:200}, {id:'unicorn', icon:'🦄', name:'Gem Unicorn', cost:5, gem:true}, {id:'phoenix', icon:'🔥', name:'Phoenix Spark', cost:8, gem:true}
];
const badges = [
  {name:'First Win', test:s=>s.totalCorrect>=1}, {name:'100 XP Club', test:s=>s.xp>=100}, {name:'Coin Collector', test:s=>s.coins>=100}, {name:'Gem Keeper', test:s=>s.gems>=5}, {name:'Boss Slayer', test:s=>s.bossWins>=1}, {name:'Mini Game Star', test:s=>s.miniWins>=5}, {name:'10 Question Hero', test:s=>s.totalAnswered>=10}, {name:'50 Question Champion', test:s=>s.totalAnswered>=50}, {name:'Accuracy Master', test:s=>s.totalAnswered>=20 && s.totalCorrect/s.totalAnswered>=.85}, {name:'Daily Finisher', test:s=>s.daily.claimed===todayKey()}, {name:'World Explorer', test:s=>unlockedWorldCount(s)>=3}, {name:'Pet Collector', test:s=>s.ownedPets.length>=3}
];
const storeKey = 'mathQuestKidsV4';
let data = loadData();
let currentId = data.currentId;
let state = getCurrent();
let currentTopicId = getAvailableTopics()[0];
let currentQuestion = null, selectedAnswer=null, placedAnswer=null, lessonIndex=0, lessonCorrect=0, bossHealth=100, bossActive=false, matched=[];

const els = {};
['profileGate','mainApp','welcomeTitle','welcomeCopy','profileNameText','classText','xpText','coinsText','gemsText','streakText','heroFace','petFace','speech','classSelector','topicGrid','missionTitle','missionStory','dailyMissionText','dailyProgress','claimDailyBtn','topicTitle','modeLabel','soundBtn','lessonProgressText','lessonProgress','questionCard','feedback','checkBtn','nextBtn','worldMap','bossBtn','bossIcon','bossName','bossStory','bossHealth','bossHealthText','newProfileName','newProfileLevel','addProfileBtn','profileList','avatarGrid','petGrid','gameZone','miniQuestion','shopGrid','badgeGrid','insightGrid','accuracyChart','weeklyChart','masteryList','resetBtn','toast'].forEach(id=>els[id]=$(id));

function emptyChild(name='Kid', level=3){return {id:'p'+Date.now()+rand(100,999),name,level:Number(level),xp:0,coins:50,gems:0,streak:0,lastSeen:'',avatar:'fox',pet:'none',ownedPets:['none'],sound:true,totalAnswered:0,totalCorrect:0,bossWins:0,miniWins:0,minutes:0,daily:{answered:0,claimed:''},topicStats:{},weekly:{},created:todayKey()};}
function loadData(){try{const saved=JSON.parse(localStorage.getItem(storeKey)); if(saved?.profiles?.length)return saved;}catch(e){} const child=emptyChild('Alex',3); return {currentId:child.id,profiles:[child]};}
function saveData(){const i=data.profiles.findIndex(p=>p.id===currentId); if(i>=0)data.profiles[i]=state; data.currentId=currentId; localStorage.setItem(storeKey,JSON.stringify(data));}
function getCurrent(){return data.profiles.find(p=>p.id===currentId)||data.profiles[0];}
function currentLevel(){return classLevels.find(l=>l.level===Number(state.level))||classLevels[2];}
function getAvailableTopics(){return currentLevel().topics;}
function topicObj(id){return {id,...allTopics[id]};}
function unlockedWorldCount(s=state){let maxWorld=0; Object.entries(s.topicStats||{}).forEach(([id,st])=>{if(st.answered>=5 && st.correct/st.answered>=.7)maxWorld=Math.max(maxWorld,(allTopics[id]?.world||0)+1);}); return Math.max(1,maxWorld);}

function init(){if(state.lastSeen!==todayKey()){state.streak = state.lastSeen ? state.streak+1 : 1; state.lastSeen=todayKey(); state.daily={answered:0,claimed:''};} saveData(); bind(); renderAll(); nextQuestion(true);}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.screen))); document.querySelectorAll('[data-screen-jump]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.screenJump))); els.checkBtn.addEventListener('click',checkAnswer); els.nextBtn.addEventListener('click',()=>nextQuestion()); els.claimDailyBtn.addEventListener('click',claimDaily); els.soundBtn.addEventListener('click',()=>{state.sound=!state.sound; renderAll(); saveData();}); els.bossBtn.addEventListener('click',startBossBattle); els.addProfileBtn.addEventListener('click',addProfile); els.resetBtn.addEventListener('click',resetCurrent); document.querySelectorAll('.mini-mode').forEach(b=>b.addEventListener('click',()=>newMiniGame(b.dataset.game)));}
function showGate(){els.profileGate.innerHTML=`<div class="gate-card"><p class="eyebrow">MathQuest Kids 4.0</p><h1>Who is learning today?</h1><p class="muted">Each child keeps separate XP, levels, rewards, and parent analytics.</p><div class="profile-list">${data.profiles.map(p=>`<div class="profile-card" data-switch="${p.id}"><h2>${avatarIcon(p.avatar)} ${p.name}</h2><p class="muted">${classLevels.find(l=>l.level==p.level).name} • ${p.xp} XP • ${p.totalAnswered} questions</p></div>`).join('')}</div><button class="primary-btn" id="gateCreate">Create New Child</button></div>`; document.querySelectorAll('[data-switch]').forEach(c=>c.addEventListener('click',()=>switchProfile(c.dataset.switch))); $('gateCreate').addEventListener('click',()=>{els.profileGate.classList.add('hidden');els.mainApp.classList.remove('hidden');showScreen('profileScreen')}); if(data.profiles.length){setTimeout(()=>{els.profileGate.classList.add('hidden');els.mainApp.classList.remove('hidden')},900);} }
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active-screen')); $(id).classList.add('active-screen'); document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.screen===id)); if(id==='parentScreen')renderParent();}

function renderAll(){state= getCurrent(); saveData(); renderHeader(); renderClassSelector(); renderTopics(); renderMap(); renderProfiles(); renderAvatars(); renderShop(); renderBadges(); renderParent(); showGate();}
function renderHeader(){const level=currentLevel(); els.profileNameText.textContent=state.name; els.classText.textContent=`${level.level}: ${level.name}`; els.xpText.textContent=state.xp; els.coinsText.textContent=state.coins; els.gemsText.textContent=state.gems; els.streakText.textContent=`${state.streak} days`; els.heroFace.textContent=avatarIcon(state.avatar); els.petFace.textContent=petIcon(state.pet); els.soundBtn.textContent=state.sound?'🔊 Sound':'🔇 Silent'; els.welcomeTitle.textContent=`${state.name}'s Math Adventure`; els.welcomeCopy.textContent=`Current path: ${level.name}. Keep solving missions to unlock worlds, pets, and trophies.`; els.dailyProgress.style.width=`${Math.min(100,state.daily.answered*10)}%`; els.claimDailyBtn.disabled=state.daily.answered<10||state.daily.claimed===todayKey();}
function renderClassSelector(){els.classSelector.innerHTML=classLevels.map(l=>`<button class="secondary-btn ${state.level==l.level?'selected':''}" data-level="${l.level}">Level ${l.level}<br><small>${l.name}</small></button>`).join(''); els.classSelector.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{state.level=Number(b.dataset.level); currentTopicId=getAvailableTopics()[0]; nextQuestion(true); renderAll();}));}
function renderTopics(){const ids=getAvailableTopics(); els.topicGrid.innerHTML=ids.map(id=>{const t=topicObj(id), st=state.topicStats[id]||{answered:0,correct:0}; const acc=st.answered?Math.round(st.correct/st.answered*100):0; return `<div class="topic ${currentTopicId===id?'active-topic':''}" data-topic="${id}"><strong>${t.icon} ${t.name}</strong><p class="muted">Mastery: ${acc}% • ${st.answered} tried</p></div>`}).join(''); els.topicGrid.querySelectorAll('.topic').forEach(card=>card.addEventListener('click',()=>{currentTopicId=card.dataset.topic; lessonIndex=0; lessonCorrect=0; nextQuestion(true); renderAll();})); const t=topicObj(currentTopicId); els.missionTitle.textContent=t.name; els.missionStory.textContent=worlds[t.world].story;}
function renderMap(){const open=unlockedWorldCount(); els.worldMap.innerHTML=worlds.map((w,i)=>{const locked=i>=open; const topicsIn=Object.keys(allTopics).filter(id=>allTopics[id].world===i); const complete=topicsIn.filter(id=>{const st=state.topicStats[id];return st?.answered>=5&&st.correct/st.answered>=.75}).length; return `<div class="world-node ${locked?'locked':''}"><div class="big">${locked?'🔒':w.icon}</div><h3>${w.name}</h3><p class="muted">${w.story}</p><div class="stars">${'★'.repeat(Math.min(3,complete))}${'☆'.repeat(3-Math.min(3,complete))}</div></div>`}).join(''); const w=worlds[topicObj(currentTopicId).world]; els.bossIcon.textContent=w.bossIcon; els.bossName.textContent=w.boss; els.bossStory.textContent=`Defeat ${w.boss} inside ${w.name}.`; updateBoss();}
function renderProfiles(){els.profileList.innerHTML=data.profiles.map(p=>`<div class="profile-card ${p.id===currentId?'selected':''}"><h3>${avatarIcon(p.avatar)} ${p.name}</h3><p class="muted">Level ${p.level} • ${p.xp} XP • ${p.totalAnswered} questions</p><button class="secondary-btn" data-switch2="${p.id}">Use Profile</button></div>`).join(''); els.profileList.querySelectorAll('[data-switch2]').forEach(b=>b.addEventListener('click',()=>switchProfile(b.dataset.switch2)));}
function renderAvatars(){els.avatarGrid.innerHTML=avatars.map(a=>`<div class="avatar ${state.avatar===a.id?'selected':''}" data-avatar="${a.id}"><h2>${a.icon}</h2><strong>${a.name}</strong><p class="muted">${a.line}</p></div>`).join(''); els.avatarGrid.querySelectorAll('.avatar').forEach(a=>a.addEventListener('click',()=>{state.avatar=a.dataset.avatar; showToast('Hero changed.'); renderAll();})); els.petGrid.innerHTML=pets.map(p=>{const owned=state.ownedPets.includes(p.id); return `<div class="avatar ${state.pet===p.id?'selected':''} ${owned?'':'locked'}" data-pet="${p.id}"><h2>${p.icon}</h2><strong>${p.name}</strong><p class="muted">${owned?'Owned':`${p.cost} ${p.gem?'gems':'coins'}`}</p></div>`}).join(''); els.petGrid.querySelectorAll('.avatar').forEach(p=>p.addEventListener('click',()=>{const id=p.dataset.pet; if(state.ownedPets.includes(id)){state.pet=id; showToast('Pet selected.'); renderAll();} else buyPet(id);}));}
function renderShop(){els.shopGrid.innerHTML=pets.filter(p=>p.id!=='none').map(p=>`<div class="shop-item"><h2>${p.icon}</h2><strong>${p.name}</strong><p>${p.cost} ${p.gem?'gems':'coins'}</p><button class="secondary-btn" data-buy="${p.id}">${state.ownedPets.includes(p.id)?'Owned':'Buy'}</button></div>`).join('')+`<div class="shop-item"><h2>🎁</h2><strong>Mystery Chest</strong><p>50 coins</p><button class="primary-btn" id="buyChestBtn">Open</button></div>`; els.shopGrid.querySelectorAll('[data-buy]').forEach(b=>b.addEventListener('click',()=>buyPet(b.dataset.buy))); $('buyChestBtn')?.addEventListener('click',buyChest);}
function renderBadges(){els.badgeGrid.innerHTML=badges.map(b=>`<div class="badge ${b.test(state)?'selected':'locked'}"><strong>${b.test(state)?'🏆':'🔒'} ${b.name}</strong></div>`).join('');}
function avatarIcon(id){return avatars.find(a=>a.id===id)?.icon||'🦊'} function petIcon(id){return pets.find(p=>p.id===id)?.icon||'✨'}

function addProfile(){const name=(els.newProfileName.value||'Kid').trim(); const child=emptyChild(name,els.newProfileLevel.value); data.profiles.push(child); currentId=child.id; state=child; currentTopicId=getAvailableTopics()[0]; els.newProfileName.value=''; showToast('Child profile created.'); renderAll(); nextQuestion(true); showScreen('learnScreen');}
function switchProfile(id){currentId=id; state=getCurrent(); currentTopicId=getAvailableTopics()[0]; lessonIndex=0; lessonCorrect=0; showToast(`Switched to ${state.name}.`); renderAll(); nextQuestion(true); showScreen('learnScreen');}

function generateQuestion(topicId=currentTopicId){const max=currentLevel().max; let a=rand(1,max), b=rand(1,Math.max(2,Math.floor(max/2))), answer, text, visual='', story='', kind=shuffle(['choice','gap','drag'])[0];
  const names=['Mia','Tobi','Ava','Leo','Zara','Noah']; const items=['apples','stars','coins','books','marbles','balloons']; const n=names[rand(0,names.length-1)], item=items[rand(0,items.length-1)];
  switch(topicId){
    case 'counting': answer=a; text=`Count the ${item}. How many are there?`; visual=visualItems(item,a); story=`${n} is arranging ${item} for a quest.`; break;
    case 'addition': answer=a+b; text=`${a} + ${b} = ?`; visual=visualItems(item,a)+'<span style="font-size:2rem">+</span>'+visualItems(item,b); story=`${n} has ${a} ${item}. A friend gives ${b} more.`; break;
    case 'subtraction': if(b>a)[a,b]=[b,a]; answer=a-b; text=`${a} - ${b} = ?`; visual=visualItems(item,a); story=`${n} has ${a} ${item}. ${b} are used for a mission.`; break;
    case 'multiplication': a=rand(2,12);b=rand(2,12);answer=a*b;text=`${a} × ${b} = ?`;visual=visualGrid(a,b);story=`There are ${a} teams with ${b} heroes each.`;break;
    case 'division': b=rand(2,12);answer=rand(2,12);a=b*answer;text=`${a} ÷ ${b} = ?`;story=`${a} gems are shared equally among ${b} children.`;visual=visualItems('gems',Math.min(a,24));break;
    case 'fractions': b=shuffle([2,3,4,5,6,8])[0];a=rand(1,b-1);answer=`${a}/${b}`;text=`What fraction of the pizza is shaded?`;visual=fractionVisual(a,b);story=`A magic pizza is divided into ${b} equal parts.`;kind='choice';break;
    case 'decimals': a=rand(1,9);b=rand(1,9);answer=((a/10)+(b/10)).toFixed(1);text=`${(a/10).toFixed(1)} + ${(b/10).toFixed(1)} = ?`;story='Add the decimal energy points.';break;
    case 'percent': a=shuffle([10,20,25,50])[0]; b=shuffle([40,60,80,100,120,200])[0]; answer=a*b/100; text=`What is ${a}% of ${b}?`; story='Find the treasure discount.';break;
    case 'ratio': a=rand(2,8); b=a*rand(2,6); answer=b/a; text=`If ${a} keys open ${b} doors, how many doors per key?`; story='Use ratio thinking.';break;
    case 'geometry': a=rand(3,12); b=rand(3,12); answer=a*b; text=`Area of a rectangle with length ${a} and width ${b}?`; visual=`<div class="visual-row">▭ length ${a}, width ${b}</div>`; story='Build the city floor tile.';break;
    case 'time': a=rand(1,10); b=rand(1,5); answer=a+b; text=`It is ${a}:00. What time is it after ${b} hours?`; story='Set the Clock Tower correctly.';break;
    case 'money': a=rand(5,50); b=rand(2,8); answer=a*b; text=`One snack costs ₦${a}. What is the cost of ${b} snacks?`; story='Shop carefully at Market Math.';break;
    case 'algebra': a=rand(2,12); b=rand(1,20); answer=a+b; text=`x - ${b} = ${a}. What is x?`; story='Unlock the rocket code.';break;
    case 'logic': a=rand(2,8); b=a+2; const c=b+2; answer=c+2; text=`Complete the pattern: ${a}, ${b}, ${c}, ?`; story='The temple door needs the next number.';break;
    default: answer=a+b;text=`${a} + ${b} = ?`;story='Solve the story problem.';
  }
  const choices=makeChoices(answer,topicId); return {kind,text,answer,choices,story,visual};
}
function makeChoices(answer,topic){if(typeof answer==='string'&&answer.includes('/')){const [n,d]=answer.split('/').map(Number);return shuffle([answer,`${Math.max(1,n-1)}/${d}`,`${Math.min(d,n+1)}/${d}`,`${n}/${d+1}`]);} const val=Number(answer); const opts=new Set([String(answer)]); while(opts.size<4){opts.add(String(val+rand(-10,10)||val+1));} return shuffle([...opts]).map(x=>isNaN(Number(x))?x:Number(x));}
function visualItems(item,count){const map={apples:'🍎',stars:'⭐',coins:'🪙',books:'📘',marbles:'🔵',balloons:'🎈',gems:'💎'}; return `<div class="visual-row">${Array.from({length:Math.min(count,24)},()=>map[item]||'●').join('')}</div>`;}
function visualGrid(r,c){let html='<div class="visual-row">'; for(let i=0;i<Math.min(r*c,36);i++)html+='🔹'; return html+'</div>';}
function fractionVisual(n,d){return `<div class="visual-row">${Array.from({length:d},(_,i)=>i<n?'🍕':'◻️').join('')}</div>`;}

function nextQuestion(reset=false){if(reset){lessonIndex=0;lessonCorrect=0;} if(lessonIndex>=10){completeLesson();lessonIndex=0;lessonCorrect=0;} currentQuestion=generateQuestion(); selectedAnswer=null; placedAnswer=null; els.feedback.textContent=''; lessonIndex++; els.topicTitle.textContent=topicObj(currentTopicId).name; els.lessonProgressText.textContent=`Question ${lessonIndex} of 10`; els.lessonProgress.style.width=`${lessonIndex*10}%`; renderQuestion(currentQuestion);}
function renderQuestion(q){const story=`<div class="story-chip">${q.story}</div>`; const visual=q.visual||''; if(q.kind==='choice'){els.questionCard.innerHTML=`${story}<div class="question-text">${q.text}</div>${visual}<div class="answer-grid">${q.choices.map(c=>`<button class="answer-btn" data-val="${c}">${c}</button>`).join('')}</div>`; document.querySelectorAll('.answer-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.answer-btn').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');selectedAnswer=normalize(btn.dataset.val)}));} else if(q.kind==='gap'){els.questionCard.innerHTML=`${story}<div class="question-text">${q.text}</div>${visual}<input class="gap-input" id="gapInput" inputmode="numeric" placeholder="Type answer" />`; setTimeout(()=>$('gapInput')?.focus(),40);} else {els.questionCard.innerHTML=`${story}<div class="question-text">${q.text}</div>${visual}<div class="drag-wrap"><div class="drop-zone" id="dropZone">Drop or tap answer here</div><div class="drag-items">${q.choices.map(c=>`<div class="drag-item" draggable="true" data-val="${c}">${c}</div>`).join('')}</div></div>`; setupDrag();}}
function normalize(v){return isNaN(Number(v))?String(v):Number(v)}
function setupDrag(){const drop=$('dropZone'); document.querySelectorAll('.drag-item').forEach(item=>{item.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',item.dataset.val)}); item.addEventListener('click',()=>placeDrag(item.dataset.val));}); drop.addEventListener('dragover',e=>e.preventDefault()); drop.addEventListener('drop',e=>{e.preventDefault();placeDrag(e.dataTransfer.getData('text/plain'))});}
function placeDrag(v){placedAnswer=normalize(v); const d=$('dropZone'); d.textContent=v; d.classList.add('filled');}
function getUserAnswer(){if(currentQuestion.kind==='choice')return selectedAnswer;if(currentQuestion.kind==='gap')return normalize(($('gapInput')?.value||'').trim());return placedAnswer;}
function checkAnswer(){const ans=getUserAnswer(); if(ans===''||ans===null||typeof ans==='undefined')return showToast('Choose or type an answer first.'); const correct=String(ans).toLowerCase()===String(currentQuestion.answer).toLowerCase(); state.totalAnswered++; state.daily.answered++; state.minutes+=1; const wk=weekKey(); state.weekly[wk]=(state.weekly[wk]||0)+1; if(!state.topicStats[currentTopicId])state.topicStats[currentTopicId]={answered:0,correct:0}; state.topicStats[currentTopicId].answered++; if(correct){state.totalCorrect++;state.topicStats[currentTopicId].correct++;lessonCorrect++;state.xp+=25;state.coins+=6;els.feedback.textContent='Correct. XP, coins, and progress earned.';els.feedback.style.color='var(--good)';els.speech.textContent=praise();playTone(620);sparkleBurst(petIcon(state.pet)); if(bossActive)damageBoss();} else {els.feedback.textContent=`Not quite. Correct answer: ${currentQuestion.answer}`;els.feedback.style.color='var(--bad)';els.speech.textContent='Good try. Mistakes help you improve.';playTone(220);} markButtons(); renderAll();}
function markButtons(){document.querySelectorAll('.answer-btn').forEach(btn=>{if(String(btn.dataset.val)===String(currentQuestion.answer))btn.classList.add('correct');else if(btn.classList.contains('selected'))btn.classList.add('wrong')});}
function completeLesson(){state.xp+=60; state.coins+=20; if(lessonCorrect>=8)state.gems+=1; showToast(lessonCorrect>=8?'Lesson mastered. 1 gem earned.':'Lesson complete. Keep practicing.');}
function praise(){return shuffle(['Brilliant!','Sharp mind!','You got it!','Math power!','Excellent work!','Your hero is leveling up!'])[0];}

function startBossBattle(){bossHealth=100;bossActive=true;showScreen('learnScreen');updateBoss();showToast('Boss battle started. Correct answers attack.');}
function damageBoss(){bossHealth=Math.max(0,bossHealth-20);els.bossIcon.classList.add('hit');setTimeout(()=>els.bossIcon.classList.remove('hit'),350);if(bossHealth===0){state.bossWins++;state.xp+=120;state.coins+=60;state.gems+=2;bossActive=false;bossHealth=100;sparkleBurst('🏆');showToast('Boss defeated. 2 gems earned.')}updateBoss();}
function updateBoss(){els.bossHealth.style.width=`${bossHealth}%`;els.bossHealthText.textContent=`Health: ${bossHealth}%`;}

function newMiniGame(type='bubble'){els.gameZone.innerHTML=''; if(type==='match')return memoryGame(); if(type==='runner')return runnerGame(); if(type==='builder')return builderGame(); bubbleGame();}
function bubbleGame(){const q=generateQuestion(shuffle(getAvailableTopics())[0]); els.miniQuestion.textContent=q.text; els.gameZone.className='bubble-zone'; q.choices.forEach((c,i)=>{const b=document.createElement('button');b.className='bubble';b.textContent=c;b.style.left=`${rand(0,72)}%`;b.style.top=`${rand(0,58)}%`;b.style.animationDelay=`${i*.18}s`;b.addEventListener('click',()=>miniAnswer(c,q.answer,()=>bubbleGame()));els.gameZone.appendChild(b);});}
function memoryGame(){els.miniQuestion.textContent='Match each equation with its answer'; els.gameZone.className='match-grid'; const pairs=[]; for(let i=0;i<4;i++){const a=rand(2,12),b=rand(2,12);pairs.push({eq:`${a}+${b}`,ans:a+b,id:i});} const cards=shuffle([...pairs.map(p=>({text:p.eq,id:p.id,type:'eq'})),...pairs.map(p=>({text:p.ans,id:p.id,type:'ans'}))]); els.gameZone.innerHTML=cards.map(c=>`<button class="match-card" data-id="${c.id}" data-type="${c.type}">${c.text}</button>`).join(''); let first=null; matched=[]; els.gameZone.querySelectorAll('.match-card').forEach(card=>card.addEventListener('click',()=>{if(card.classList.contains('done'))return; if(!first){first=card;card.classList.add('selected');return;} if(first.dataset.id===card.dataset.id && first.dataset.type!==card.dataset.type){first.classList.add('done');card.classList.add('done');matched.push(card.dataset.id);state.xp+=10;state.coins+=3;if(matched.length===4){state.miniWins++;state.gems++;showToast('Memory complete. 1 gem earned.')}} else showToast('Try another pair.'); first.classList.remove('selected'); first=null; renderAll();}));}
function runnerGame(){const q=generateQuestion(shuffle(['addition','subtraction','multiplication','division'])[0]); els.miniQuestion.textContent=q.text; els.gameZone.className=''; const choices=q.choices.slice(0,3); if(!choices.map(String).includes(String(q.answer)))choices[0]=q.answer; els.gameZone.innerHTML=`<div class="runner-track"><span class="runner" id="runner">${avatarIcon(state.avatar)}</span></div><div class="lane-buttons">${shuffle(choices).map(c=>`<button class="lane-btn" data-val="${c}">${c}</button>`).join('')}</div>`; document.querySelectorAll('.lane-btn').forEach(btn=>btn.addEventListener('click',()=>miniAnswer(btn.dataset.val,q.answer,()=>runnerGame(),true)));}
function builderGame(){const a=rand(2,12),b=rand(2,12),answer=a+b; els.miniQuestion.textContent='Build the correct equation'; els.gameZone.className=''; els.gameZone.innerHTML=`<div class="builder-line"><div class="builder-slot" id="slot1">?</div><span>+</span><div class="builder-slot" id="slot2">?</div><span>=</span><div class="builder-slot" id="slot3">${answer}</div></div><div class="drag-items">${shuffle([a,b,answer,rand(1,12),rand(1,12)]).map(x=>`<div class="builder-piece" data-val="${x}">${x}</div>`).join('')}</div><button class="primary-btn" id="checkBuilder">Check Builder</button>`; let slot=1; document.querySelectorAll('.builder-piece').forEach(p=>p.addEventListener('click',()=>{if(slot<=2){$('slot'+slot).textContent=p.dataset.val;slot++;}})); $('checkBuilder').addEventListener('click',()=>{const ok=Number($('slot1').textContent)+Number($('slot2').textContent)===answer; miniAnswer(ok?answer:'x',answer,()=>builderGame());});}
function miniAnswer(c,answer,next,runner=false){if(String(c)===String(answer)){state.xp+=20;state.coins+=8;state.miniWins++; if(runner)$('runner').style.left='82%'; sparkleBurst('🎈'); showToast('Correct mini-game answer.');} else showToast(`Oops. Correct answer: ${answer}`); renderAll(); setTimeout(next,800);}
function claimDaily(){if(state.daily.answered<10||state.daily.claimed===todayKey())return; state.daily.claimed=todayKey(); state.coins+=75; state.gems+=1; state.xp+=100; sparkleBurst('🎁'); showToast('Daily chest: 75 coins, 1 gem, 100 XP.'); renderAll();}
function buyPet(id){const p=pets.find(x=>x.id===id); if(!p||state.ownedPets.includes(id))return; if(p.gem){if(state.gems<p.cost)return showToast('Not enough gems yet.'); state.gems-=p.cost;} else {if(state.coins<p.cost)return showToast('Not enough coins yet.'); state.coins-=p.cost;} state.ownedPets.push(id); state.pet=id; sparkleBurst(p.icon); showToast(`${p.name} unlocked.`); renderAll();}
function buyChest(){if(state.coins<50)return showToast('You need 50 coins.'); state.coins-=50; const prize=shuffle(['coins','xp','gem'])[0]; if(prize==='coins'){const v=rand(25,120);state.coins+=v;showToast(`Chest gave ${v} coins.`);} if(prize==='xp'){const v=rand(40,130);state.xp+=v;showToast(`Chest gave ${v} XP.`);} if(prize==='gem'){state.gems+=1;showToast('Chest gave 1 gem.');} sparkleBurst('🎁'); renderAll();}

function renderParent(){const acc=state.totalAnswered?Math.round(state.totalCorrect/state.totalAnswered*100):0; let weakest='None yet', strongest='None yet', low=101, high=-1; Object.keys(allTopics).forEach(id=>{const st=state.topicStats[id]; if(st&&st.answered>=2){const a=st.correct/st.answered*100; if(a<low){low=a;weakest=allTopics[id].name;} if(a>high){high=a;strongest=allTopics[id].name;}}}); const rec=weakest==='None yet'?'Complete at least 2 questions in each active topic.':`Spend 10 focused minutes on ${weakest}.`; els.insightGrid.innerHTML=`<div class="insight"><span>Accuracy</span><br><strong>${acc}%</strong></div><div class="insight"><span>Questions</span><br><strong>${state.totalAnswered}</strong></div><div class="insight"><span>Minutes</span><br><strong>${state.minutes}</strong></div><div class="insight"><span>Strongest</span><br><strong style="font-size:1rem">${strongest}</strong></div><div class="insight"><span>Advice</span><br><strong style="font-size:.9rem">${rec}</strong></div>`; renderCharts(); els.masteryList.innerHTML=getAvailableTopics().map(id=>{const t=allTopics[id], st=state.topicStats[id]||{answered:0,correct:0}; const a=st.answered?Math.round(st.correct/st.answered*100):0; return `<div class="mastery-row"><strong>${t.icon} ${t.name}</strong><div class="progress-bar"><div style="width:${a}%"></div></div><span>${a}%</span></div>`}).join('');}
function renderCharts(){const ids=getAvailableTopics(); els.accuracyChart.innerHTML=ids.map(id=>{const st=state.topicStats[id]||{answered:0,correct:0}; const a=st.answered?Math.round(st.correct/st.answered*100):0; return `<div class="bar-row"><span>${allTopics[id].name}</span><div class="chart-bar"><div style="width:${a}%"></div></div><strong>${a}%</strong></div>`}).join(''); const weeks=Object.keys(state.weekly).slice(-6); els.weeklyChart.innerHTML=(weeks.length?weeks:[weekKey()]).map(w=>{const v=state.weekly[w]||0; return `<div class="bar-row"><span>${w}</span><div class="chart-bar"><div style="width:${Math.min(100,v*5)}%"></div></div><strong>${v}</strong></div>`}).join('');}
function resetCurrent(){if(!confirm('Reset this child only?'))return; const old=state; const fresh=emptyChild(old.name,old.level); fresh.id=old.id; data.profiles[data.profiles.findIndex(p=>p.id===old.id)]=fresh; state=fresh; currentTopicId=getAvailableTopics()[0]; saveData(); renderAll(); nextQuestion(true); showToast('Current child reset.');}
function showToast(msg){els.toast.textContent=msg;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2300);}
function sparkleBurst(icon){for(let i=0;i<18;i++){const s=document.createElement('span');s.className='sparkle';s.textContent=icon||'⭐';s.style.left=`${rand(10,90)}vw`;s.style.top=`${rand(45,82)}vh`;s.style.animationDelay=`${i*25}ms`;document.body.appendChild(s);setTimeout(()=>s.remove(),1200);}}
function playTone(freq){if(!state.sound)return; const C=window.AudioContext||window.webkitAudioContext; if(!C)return; const ctx=new C(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=freq;gain.gain.value=.04;osc.connect(gain);gain.connect(ctx.destination);osc.start();setTimeout(()=>{osc.stop();ctx.close();},120);}
init();
